.catalog:
  name: "zookeeper"
  version: "v1.0"
  description: "Zookeeper container"
  minimum_rancher_version: v0.44.0
  uuid: "094386fd-6d3f-4c4d-aabb-e3dffea5c2f2"
  questions:
  - variable: "HOSTNAME"
    label: "Hostname"
    description: "addressable hostname for this node (Exhibitor will forward users of the UI to this address) e.g. test"
    default: ""
    required: true
    type: "string"
  - variable: "DOMAIN"
    label: "domain"
    description: "Domain part of the FQDN (e.g. digital-blue.biz)"
    default: "digital-blue.biz"
    required: true
    type: "string"
  - variable: "S3_BUCKET"
    label: "S3 Bucket"
    description: "(optional) bucket and key used by Exhibitor for backups and coordination (e.g. test-bucket:key)" 
    default: ""
    required: false
    type: "string"
  - variable: "S3_PREFIX"
    label: "S3 Prefix"
    description: "(optional) key prefix within S3_BUCKET to use for this cluster"
    default: ""
    required: false
    type: "string"
  - variable: "AWS_ACCESS_KEY_ID"
    label: "AWS Access Key ID"
    description: "(optional) AWS access key ID with read/write permissions on S3_BUCKET"
    default: ""
    required: false
    type: "string"
  - variable: "AWS_SECRET_ACCESS_KEY"
    label: "AWS_SECRET_ACCESS_KEY"
    description: "(optional) secret key for AWS_ACCESS_KEY_ID"
    default: ""
    required: false
    type: "string"
  - variable: "AWS_REGION"
    label: "AWS Region"
    description: "(optional) the AWS region of the S3 bucket"
    default: "eu-central-1"
    required: false
    type: "string"
  - variable: "ZK_PASSWORD"
    label: "ZK Password"
    description: "(optional) the HTTP Basic Auth password for the 'zk' user"
    default: ""
    required: false
    type: "string"
  - variable: "ZK_DATA_DIR"
    label: "ZK Data dir"
    description: "(optional) Zookeeper data directory"
    default: ""
    required: false
    type: "string"
  - variable: "ZK_LOG_DIR"
    label: "ZK Log dir"
    description: "(optional) Zookeeper log directory"
    default: ""
    required: false
    type: "string"
