name: "Taiga"
description: "Project management platform for agile developers"
version: "v0.2"
category: "Agile"
maintainer: "matteo.ferraroni@gmail.com"
license: "GPL"
projectURL: "http://www.google.it"
