name: "Zookeeper"
description: "Zookeeper service managed by exibitor"
version: "1.0"
category: "Infrastructure"
maintainer: "matteo.ferraroni@digital-blue.biz"
license: "GPL"
projectURL: "http://www.google.it"
