gogs:
    image: gogs/gogs:latest
    ports:
        - ${http_port}:3000
        - ${ssh_port}:22
    links:
        - mysql:db

mysql:
    image: mysql:latest
    ports:
        - ${public_port}:3306
    environment:
        MYSQL_ROOT_PASSWORD: ${mysql_password}

nerve:
    image: mferraroni/nerve
    environment:
        MACHINEID: gogs
        SERVICE_NAME: gogs
        SERVICE_HOST: www
        SERVICE_PORT: 3000
        TYPE: http
    links:
        - gogs:www
