.catalog:
  name: "Gogs"
  version: "v0.8.43"
  description: "A painless self-hosted Git service"
  uuid: a3e74b77-77b8-4774-a3c2-6179dfec99cb
  minimum_rancher_version: v0.51.0
  questions:
    - variable: public_port
      description: "public port to access the mysql server"
      label: "Public Port"
      required: true
      default: "3306"
      type: "int"
    - variable: http_port
      description: "http port to access gogs webui"
      label: "Http Port"
      required: true
      default: "10080" 
      type: "int"
    - variable: ssh_port
      description: "ssh port to access gogs cli"
      label: "Ssh Port"
      required: true
      default: "222"
      type: "int"
    - variable: mysql_password
      description: "mysql root password"
      label: "Mysql Password"
      required: true
      default: "password"
      type: "string"

gogs:
